---
author: 'Samuel Abbott'
date: 'April 2019'
division: 'Bristol Medical School: Population Health Sciences'
advisor: 'Ellen Brooks Pollock'
altadvisor: 'Hannah Christensen'
department: 'Faculty of Health Sciences'
title: 'Modelling BCG vaccination in the UK'
subtitle: 'What is the impact of changing policy?'
wordcount: "26,067"
knit: bookdown::render_book
site: bookdown::bookdown_site
always_allow_html: yes
output: 
  thesisdown::thesis_pdf: default
  #thesisdown::thesis_gitbook: default
  #thesisdown::thesis_word: default
  #thesisdown::thesis_epub: default
abstract: >
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = ' ')`
acknowledgements: >
  Thank you to Ellen Brooks-Pollock and Hannah Christensen, for supervising this thesis and for providing guidance and support. I would also like to Matthew Hickman for providing additional supervisory support. \par
 
  This thesis could not have been completed with out the support of the Tuberculosis section at Public Health England. Of particular help were: Maeve K Lalor, Dominik Zenner, and Colin Campbell. Mary Ramsay, also at Public Health England, provided invaluable insights. \par
  
  Nicky Welton provided support with the statistical methodology used in Chapter 7 - thank you. \par
  
  This work was funded by the National Institute for Health Research Health Protection Research Unit (NIHR HPRU) in Evaluation of Interventions at University of Bristol in partnership with Public Health England. Thank you for this opportunity. \par
  
  Thank you to my friends and family for providing support over 4 years. \par
  
  Finally, thank you to my partner, Venexia Walker, without whom this would definitely have gone unfinished.
bibliography: bib/thesis.bib
#Download your specific bibliography database file and refer to it in the line above.
csl: csl/bmj.csl
#Download your specific csl file and refer to it in the line above.
lot: true
lof: true
space_between_paragraphs: true
#Delete the # at the beginning of the previous line if you'd like
#to have a blank new line between each paragraph
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage[table]{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the thesis.Rmd file and then knit again.
-->

```{r knitr-options, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 320, 
                      fig.width = 8, fig.height = 8,
                      out.width = "80%", fig.align = 'center')
```

```{r include_packages, include = FALSE}
#This chunk ensures that the thesisdown package is
#installed and loaded. This thesisdown package includes
#the template files for the thesis.
if (!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if (!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
if (!require(tidyverse))
  install.packages("tidyverse", repos = "http://cran.rstudio.com")
PaperTheme <- ggplot2::theme_minimal() +
  theme(legend.position = "top")
ggplot2::theme_set(PaperTheme)
```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->
